#!/usr/bin/env python3
"""
Fetch Rockford-area occurrences from the Paleobiology Database and write
a gap-analysis report comparing PBDB taxa against the guide's manifest.js.

Usage:  python3 pbdb_fetch.py        # refresh data/*.json and rewrite pbdb_gaps.md
        python3 pbdb_fetch.py --analyze-only   # just rewrite the report from cached JSON
"""
import argparse, json, collections, re, os, sys, subprocess
from pathlib import Path

HERE = Path(__file__).resolve().parent
STRATA = ["Cerro+Gordo", "Lithograph+City", "Lime+Creek", "Shell+Rock"]
PBDB = "https://paleobiodb.org/data1.2/occs/list.json"
SHOW = "ident,coll,strat,coords,phylo"

def fetch():
    for strat in STRATA:
        fn = HERE / (strat.replace("+", "_") + ".json")
        url = f"{PBDB}?strat={strat}&show={SHOW}&limit=all"
        print(f"  GET {url}")
        # curl works around python ssl-cert issues on some macs
        subprocess.run(["curl", "-sS", url, "-o", str(fn)], check=True)

def is_rockford(r):
    if r.get("smb") and "cerro gordo" in r["smb"].lower(): return True
    if r.get("cnm") and "rockford"    in r["cnm"].lower(): return True
    return False

def load_recs():
    seen = {}
    for strat in STRATA:
        fn = HERE / (strat.replace("+","_") + ".json")
        d = json.load(open(fn))
        for r in d.get("records", []):
            seen[r["oid"]] = r
    return list(seen.values())

# Extract the genera/species currently in manifest.js. We parse the file
# rather than re-encoding the list here so the script stays in sync.
MANIFEST = HERE.parent / "manifest.js"
def manifest_taxa():
    text = MANIFEST.read_text()
    pairs = set()
    # crude regex: { genus: "X", species: "y", ...
    for m in re.finditer(r'genus:\s*"([^"]+)"\s*,\s*species:\s*"([^"]*)"', text):
        g = m.group(1).strip()
        s = m.group(2).strip().rstrip(".")  # strip "sp." -> "sp"
        # Skip placeholder genera the manifest uses for group photos
        if g.lower() in ("horn corals", "gastropods", "gastropod", "bivalves",
                         "crinoid", "bryozoan", "unknown", '"tubey belt"'):
            continue
        pairs.add((g, s))
    return pairs

def report():
    recs = load_recs()
    rfd = [r for r in recs if is_rockford(r)]

    have = manifest_taxa()
    have_g = {g.lower() for g, s in have}
    have_gs = {(g.lower(), s.lower()) for g, s in have}

    gen_count = collections.Counter()
    gen_phyl = {}
    gen_species = collections.defaultdict(collections.Counter)
    for r in rfd:
        g = r.get("idg") or r.get("gnl") or r.get("tna")
        if not g: continue
        s = r.get("ids", "")
        gen_count[g] += 1
        gen_species[g][s] += 1
        if g not in gen_phyl:
            gen_phyl[g] = (r.get("phl"), r.get("cll"), r.get("odl"), r.get("fml"))

    out = []
    out.append("# Rockford PBDB gap analysis\n")
    out.append(f"Source: Paleobiology Database — occurrences in the Cerro Gordo Mbr "
               f"(Lime Creek Fm) and 'Rockford'-named collections. "
               f"Counts are *occurrences* (proxy for how often a taxon has been documented), "
               f"not raw abundance.\n")
    out.append(f"Total Rockford-area occurrences: **{len(rfd)}** in **{len(gen_count)}** genera.\n")
    out.append("Generated by `pbdb_fetch.py`. Re-run to refresh.\n")

    out.append("## Missing genera (not currently in `manifest.js`)\n")
    out.append("### Common (≥4 PBDB occurrences)\n")
    out.append("| count | genus | order/family | species reported |")
    out.append("| ---: | --- | --- | --- |")
    miss_common, miss_rare = [], []
    for g, n in gen_count.most_common():
        if g.lower() in have_g: continue
        (miss_common if n >= 4 else miss_rare).append((g, n))
    for g, n in miss_common:
        info = gen_phyl[g]; grp = info[2] or info[3] or info[1] or "?"
        specs = ", ".join(f"{s or 'sp.'}({c})" for s, c in gen_species[g].most_common())
        out.append(f"| {n} | *{g}* | {grp} | {specs} |")
    out.append("")
    out.append("### Rare (1–3 PBDB occurrences)\n")
    out.append("| count | genus | order/family | species reported |")
    out.append("| ---: | --- | --- | --- |")
    for g, n in miss_rare:
        info = gen_phyl[g]; grp = info[2] or info[3] or info[1] or "?"
        specs = ", ".join(f"{s or 'sp.'}({c})" for s, c in gen_species[g].most_common())
        out.append(f"| {n} | *{g}* | {grp} | {specs} |")

    out.append("\n## Species-level gaps within genera we already cover\n")
    out.append("(Additional species reported by PBDB for genera that are already in the guide.)\n")
    for g, sc in sorted(gen_species.items()):
        if g.lower() not in have_g: continue
        extras = [(s, c) for s, c in sc.items() if s and (g.lower(), s.lower()) not in have_gs]
        if not extras: continue
        out.append(f"- **{g}** — already have: " +
                   ", ".join(sorted(s or 'sp.' for gg, s in have if gg.lower() == g.lower())))
        for s, c in sorted(extras, key=lambda x:-x[1]):
            out.append(f"    - +{c}  *{g} {s}*")

    out_path = HERE / "pbdb_gaps.md"
    out_path.write_text("\n".join(out) + "\n")
    print(f"Wrote {out_path}")

if __name__ == "__main__":
    p = argparse.ArgumentParser()
    p.add_argument("--analyze-only", action="store_true",
                   help="skip the PBDB fetch and re-run the analysis on cached JSON")
    args = p.parse_args()
    if not args.analyze_only:
        fetch()
    report()
